### ISSUE TITLE
WinEvent.Active behaves inconsistently when handling the window of ApplicationFrameHost.exe compared to regular windows.

### ISSUE THREAD

**Issue by Giresharu** [Descolada/AHK-v2-libraries#10]
Here is my minimal code:
```ahk
WinEvent.Active((h, w, d) => ToolTip(w " Actived"))
```

When a regular window is created, it also counts as an Active event, triggering the callback of this line of code. However, when an ApplicationFrameHost.exe window (such as the Windows 10 settings window) is created, this callback is not triggered. Is this a feature or a bug?

**Comment by Giresharu** [comment]
Well, I tried many times before, but surprisingly, after I restarted my computer, the issue was resolved. I think this issue can be closed now.

**Comment by Descolada** [comment]
If that problem persists, try updating the library. I've just pushed a big update which adds some features and fixes some bugs (and probably introduces new ones ;) ).
