### ISSUE TITLE
Recent WinEvent.ahk changes causing side effects

### ISSUE THREAD

**Issue by Tomshiii** [Descolada/AHK-v2-libraries#11]
I'm not sure how to easily explain this, or really explain it in a way that might make sense but I'll try to do my best.
I have a [script](https://github.com/Tomshiii/ahk/blob/dev/lib/Classes/Editors/Premiere_RightClick.ahk) that allows me to move the playhead within Premiere Pro using a mouse button. Within this script I also [set two hotkeys](https://github.com/Tomshiii/ahk/blob/a48d64e58a7f47d79c0a53fd034eaf71e662c245/lib/Classes/Editors/Premiere_RightClick.ahk#L256) so that clicking either <kbd>LButton</kbd> or <kbd>XButton2</kbd> [during the loop](https://github.com/Tomshiii/ahk/blob/a48d64e58a7f47d79c0a53fd034eaf71e662c245/lib/Classes/Editors/Premiere_RightClick.ahk#L426) will change some class variables so that when <kbd>RButton</kbd> is released different things may happen.

Previously this worked no problem, but after the recent changes these values no longer get updated while [`WinEvent.NotActive`](https://github.com/Tomshiii/ahk/blob/a48d64e58a7f47d79c0a53fd034eaf71e662c245/lib/Classes/Editors/Premiere_RightClick.ahk#L337) is present. Removing that line alone (or reverting changes made to WinEvent in my repo) is the only way to return usual functionality.

The reason for things breaking as far as I can tell seems to be this change on [line 313](https://github.com/Descolada/AHK-v2-libraries/blob/24a8ff690ab6744365cd3a13ed10807cde52121b/Lib/WinEvent.ahk#L313);
```diff
-this.pCallback := CallbackCreate(callbackFunc, "C", 7)
+this.pCallback := CallbackCreate(callbackFunc, "C Fast", 7)
```
Reverting this line alone seems to return previous functionality. I won't pretend to understand how that ties into the overall lib so if that's just how it's gotta be now then so be it feel free to let me know and I'll just freeze the previous version in my repo. Just thought I would mention it on the off chance that it's an avoidable scenario.

Thank you for your time and all the work you've put into this script! It's awesome.
Let me know if there's anything else you might need from me, happy to help however I can.

**Comment by Descolada** [comment]
Thank you for reporting this! That was an accidental addition and shouldn't have been there, it has now been removed.
