### ISSUE TITLE
`array.Join` should be corrected

### ISSUE THREAD

**Issue by vmech** [Descolada/AHK-v2-libraries#13]
https://github.com/Descolada/AHK-v2-libraries/blob/0b7dd26635ef1122c7492136f590a9f280773352/Lib/Array.ahk#L290-L291
Maybe this will be enough ?
```autohotkey
for v in this
	if isset(v)
		result .= v delim
```
Not sure if it would really make sense to add just a separator, without a value, in this case.

**Comment by Descolada** [comment]
Fixed. I think `unset` should be treated as an empty string in the case of Join, as it is done in Javascript also.
